### ISSUE TITLE
Unexpected game ending bug

### ISSUE THREAD

**Issue by arrtych** [Nodemons/g2moku#3]
If you click on already used tile game ends

**Comment by 4matic** [comment]
Agree, need to fix this 💃

**Comment by arrtych** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unexpected game ending bug](https://trello.com/c/aujkOFST/8-unexpected-game-ending-bug)

**Comment by 4matic** [comment]
Closing due to overall refactoring
